services:
#  api:
#    build: .
#    command: uvicorn app.main:app --host 0.0.0.0
#    volumes:
#      - .:/app
#    ports:
#      - '8000'
#    environment:
#      - DATABASE_URL=postgresql://postgres:postgrespwd@db:5432/birth-tunes
#    depends_on:
#      - postgres
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespwd
      - POSTGRES_DB=birth-tunes
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=password
      # 볼륨 설정
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
