"""change column name: content_url -> youtube_video_id

Revision ID: 65abbb7d178e
Revises: 9139609ae382
Create Date: 2023-08-20 18:11:24.330772

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65abbb7d178e"
down_revision: Union[str, None] = "9139609ae382"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "song", sa.Column("youtube_video_id", sa.String(length=100), nullable=True)
    )
    op.drop_column("song", "content_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "song",
        sa.Column("content_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("song", "youtube_video_id")
    # ### end Alembic commands ###
