"""change unique index to use only base_date

Revision ID: 7423197cd438
Revises: 94d521b524fa
Create Date: 2023-09-03 19:24:10.756107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7423197cd438'
down_revision: Union[str, None] = '94d521b524fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('song_base_date_music_chart_id_key', 'song', type_='unique')
    op.drop_index('ix_song_base_date', table_name='song')
    op.create_index(op.f('ix_song_base_date'), 'song', ['base_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_base_date'), table_name='song')
    op.create_index('ix_song_base_date', 'song', ['base_date'], unique=False)
    op.create_unique_constraint('song_base_date_music_chart_id_key', 'song', ['base_date', 'music_chart_id'])
    # ### end Alembic commands ###
