"""add index to song.base_date

Revision ID: 94d521b524fa
Revises: 65abbb7d178e
Create Date: 2023-08-20 19:12:52.296544

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94d521b524fa"
down_revision: Union[str, None] = "65abbb7d178e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_song_base_date"), "song", ["base_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_song_base_date"), table_name="song")
    # ### end Alembic commands ###
