name: Wake up periodically
on:
  schedule:
    - cron: "0 0 * * 3"  # 매주 수요일 자정에 실행
  workflow_dispatch:  # 수동 실행용
jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send request
        run: |
          curl --request GET --url https://birth-tunes-backend.fly.dev/songs/1988/4/30 \
            --header "nfteam-api-token: ${{ secrets.NFTEAM_API_TOKEN }}"
